---
ID: "c62f8ae4-5ec5-44d6-b6a8-f253c502f565"
Parent: "65fbfcfe-f621-4777-9c6a-0fa1265a2f1d"
Template: "a87a00b1-e6db-45ab-8b54-636fec3b5523"
Path: "/sitecore/templates/Branches/Project/uniform-jss/CommonPage/$name/local"
DB: master
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: business/16x16/index.png
Languages:
- Language: en
  Fields:
  - ID: "b5e02ad9-d56f-4c41-a065-a133db87bdeb"
    Hint: __Display name
    Value: Local Page Content
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200730T152202Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
