---
ID: "3ddc753f-7f47-4787-96bb-88d077845cd6"
Parent: "f30254f9-4475-4ec1-86c5-70ec82418698"
Template: "44ab5107-3c73-42f0-a427-bec549f944b9"
Path: "/sitecore/system/Marketing Control Panel/Profiles/uniform-jss/Uniform Interest/Security"
DB: master
SharedFields:
- ID: "12e2c64a-5f08-4948-86c8-55ae06afeef8"
  Hint: MaxValue
  Value: 10
Languages:
- Language: en
  Fields:
  - ID: "2e1a9aab-f7c1-49ee-b032-28b98d3688d6"
    Hint: Name
    Value: Security
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20200731T021921Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
