version: "2.4"

services:
  solr:
    image: mcr.microsoft.com/dotnet/framework/aspnet:4.8-windowsservercore-${windowsservercore_version}
    mem_limit: 4GB

networks:
  default:
    external:
      name: nat
