/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.
import Hero from './renderings/Hero';

const components = new Map();
components.set('Hero', Hero);

export default function componentFactory(componentName) {
  return components.get(componentName);
}
